// AUTO-GENERATED by scripts/generate-releases.mjs.
// Run `npm run gen:releases` after each commit to refresh.
// Do not edit this file by hand — your changes will be overwritten.

export interface ReleaseFeature {
  title: string;
  description: string;
}

export interface Release {
  version: string;
  name: string;
  date: string; // ISO yyyy-mm-dd
  summary: string;
  features: ReleaseFeature[];
}

export const RELEASES: Release[] = [
  {
    "version": "#73b31c6",
    "name": "Tag enrichment + auto-discovered categories with archetype quiz results",
    "date": "2026-05-31",
    "summary": "Two features that give the quiz generator richer signal: per-product tag",
    "features": [
      {
        "title": "Dashboard \"Enrich tags\" button with auto-loop",
        "description": "a single click chews through the whole catalog one batch at a time, showing live progress \"Enriching 30 / 87…\" and a summary banner with per-category error counts at the end"
      },
      {
        "title": "/app/categories admin page with grid of category cards…",
        "description": "(name, description, tag chips, product count, rationale tooltip) and a Discover / Re-discover button. Sidebar entry under Workspace"
      },
      {
        "title": "Recommendation engine archetype branch",
        "description": "when a result page has match_strategy=\"archetype\" and category_product_ids (inlined by the publisher), the engine returns the bucket ranked by in-stock + price. Falls through to existing top_n behavior otherwise so legacy quizzes are byte-identical"
      }
    ]
  },
  {
    "version": "#879c7cf",
    "name": "New Quiz Customize panel, releases UI, brand voice cascade",
    "date": "2026-05-30",
    "summary": "Three follow-on features layered on top of the v2 phases.",
    "features": [
      {
        "title": "Collapsible \"Customize\" panel under the goal prompt with…",
        "description": "Style (theme preset + tone), Flow (welcome / email gate / preview / AskAI / end / mixed inputs), Embed (floating launcher), Integrations (webhook stub)"
      },
      {
        "title": "Bias + post-process",
        "description": "settings append to SYSTEM_PROMPT; theme tokens, launcher_config, and integration stub are applied deterministically to the generated doc via applyPostGeneration. Existing minimal-input flow stays byte-identical when settings are absent"
      },
      {
        "title": "New `QzTooltip` primitive (hover on desktop, tap-toggle on…",
        "description": "touch, Escape + outside-click to dismiss) in app/components/qz.tsx"
      }
    ]
  },
  {
    "version": "#55dda7a",
    "name": "Dashboard cleanup, auto-generated releases, brand voice changes theme",
    "date": "2026-05-30",
    "summary": "Remove redundant Activity / What changed card",
    "features": [
      {
        "title": "Dashboard right column now contains only the WhatsNewCard",
        "description": "The page-header sync banner above already covers sync state, so the Activity rows duplicated what's in the releases card"
      },
      {
        "title": "Every entry in BRAND_VOICE_PRESETS gains a full…",
        "description": "visual_suggestions.tokens (colors, typography, radius, button_style, spacing) hand-tuned to match the archetype:"
      },
      {
        "title": "Bold & disruptive → Space Grotesk 700, yellow-on-black, pill",
        "description": "Bold & disruptive → Space Grotesk 700, yellow-on-black, pill"
      }
    ]
  },
  {
    "version": "#bf61654",
    "name": "Filter releases generator to UI-only features",
    "date": "2026-05-30",
    "summary": "way too noisy. Merchants care about visual surface changes, not the AI",
    "features": [
      {
        "title": "New looksLikeUI() regex weighs UI surface keywords (card,…",
        "description": "drawer, tab, page, panel, sidebar, modal, popover, tooltip, banner, badge, pill, chip, menu, picker, wizard, canvas, button, icon, theme, color, font, layout, route, mobile, admin, storefront, etc.) against backend signals (SDK, endpoint, Prisma, migration, Zod, schema, system prompt, tool- use, server-side, lib helpers, retries). A bullet is kept only when UI hits ≥ backend hits."
      }
    ]
  },
  {
    "version": "#6cecec0",
    "name": "Quiz App v2 phases 1–3: builder rewrite, branching, AskAI",
    "date": "2026-05-29",
    "summary": "Phase 1 — Builder rewrite",
    "features": [
      {
        "title": "New node types",
        "description": "message, end (intro relabeled \"welcome\")"
      },
      {
        "title": "Per-node breakpoint_overrides (desktop/mobile token layer)",
        "description": "Per-node breakpoint_overrides (desktop/mobile token layer)"
      },
      {
        "title": "Drawer collapsed 5 tabs → 3 (Preview / Content / Design)",
        "description": "Drawer collapsed 5 tabs → 3 (Preview / Content / Design)"
      }
    ]
  },
  {
    "version": "#1a98199",
    "name": "Quiz App v2 phases 4–6: presets, freeform/searchable/picker, integrations, launcher, mobile",
    "date": "2026-05-29",
    "summary": "Phase 4 — Theme presets + Text/Email questions",
    "features": [
      {
        "title": "Five curated theme packs (Minimal, Editorial, Bold, Pastel,…",
        "description": "Dark) with one-click apply from the brand design page"
      },
      {
        "title": "New question_type values \"text\" and \"email\" with optional…",
        "description": "input_config (placeholder, max_length); freeform types use a single seed answer for tag accumulation + edge routing"
      },
      {
        "title": "Visible \"product_cards\" node",
        "description": "1–6 merchant-picked products rendered as themed cards with PDP links"
      }
    ]
  },
  {
    "version": "#39e9bde",
    "name": "Initial commit: full Quizocalypse MVP",
    "date": "2026-05-27",
    "summary": "webhook handlers for products/collections/inventory/uninstall, auto-resync",
    "features": [
      {
        "title": "M4 Visual Flow Builder",
        "description": "React Flow canvas, per-answer source handles, drag-to-connect, add/remove answers + nodes, dagre auto-layout, validation overlay, right-side drawer with Content/Logic/Preview/Design/AI tabs."
      },
      {
        "title": "M5 Brand Design Editor",
        "description": "Shop-level brand tokens + per-node overrides, shop → quiz → node cascade resolved at publish, WCAG AA contrast warnings, live preview, Google Fonts injection in the storefront."
      },
      {
        "title": "M6 Recommendation Engine",
        "description": "pure tag-overlap scoring with in-stock + price tie-breaks, fallback collection on score=0; \"View all paths\" debugger modal; live preview tab in result drawer."
      }
    ]
  },
  {
    "version": "#077012d",
    "name": "Progressive product previews mid-quiz",
    "date": "2026-05-27",
    "summary": "Adds a sticky right rail (desktop) / collapsible chip (mobile) that",
    "features": [
      {
        "title": "Layout switches via inline media-query styles",
        "description": "≥900px → flex-row with sticky 320px rail; <900px → centered column + fixed-position chip."
      },
      {
        "title": "Preview hides on the result page (the result has its own…",
        "description": "product list). `Reset` clears the preview-viewed flag so a \"start over\" re-arms tracking."
      },
      {
        "title": "`ContentTab` for question nodes gains a styled checkbox",
        "description": "\"Show product preview after this question\" with descriptive helper text."
      }
    ]
  }
];

// Compact dashboard card shows the most recent N releases.
export const LATEST_RELEASES = RELEASES.slice(0, 4);
